name: algorithm
description: "Mobile Client for Algorithm 8.0."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cloud_firestore: ^4.8.4
  firebase_core: ^2.16.0
  firebase_auth: ^4.7.2
  uuid: ^4.3.3
  lottie: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  ionicons: ^0.2.2
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.2.0
  webview_flutter: ^4.5.0
  url_launcher: ^6.2.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
